package toolplugin

// Source: plugins/tools.ts and bundled specifications @[543de4f3].
// Built-in descriptions and executors have one native owner.
func builtinPlugin() Plugin {
	return Plugin{ID: "builtin.frontends", Module: "builtin/native", Tools: []Tool{
		{Specification: []byte("{\"type\":\"custom\",\"name\":\"mcat\",\"description\":\"Read one or more UTF-8 files or inclusive logical-line ranges as raw rows; --number prefixes source line numbers like nl -ba.\\nUsage: mcat [-n N] [--max-tokens N] [--tail] [--number] PATH [START:END ...] [PATH [START:END ...] ...]\\n\\nSTART:END or START-END is a separate operand after its path, inclusive of both endpoints. Several ranges may follow one path; at most 16 reads are allowed. -n counts rows within a single range and retains the default token ceiling.\\nExamples:\\n  mcat src/main.go 100:150                # rows 100\\u2013150 (51 rows)\\n  mcat -n 20 src/main.go                  # first 20 rows\\n  mcat --number src/main.go 100:150       # source line prefixes\\n  mcat src/main.go 10:40 src/config.go 1:30\\n\\nLimited output contains complete rows and exits nonzero; retained omissions provide per-file mread recovery.\"}"), NativeExecutor: "mcat"},
		{Specification: []byte("{\"type\":\"custom\",\"name\":\"msymbol\",\"description\":\"Resolve current Go, JavaScript, TypeScript, JSON, or Python symbol with compact definition bodies and references grouped by file. Before removing a field or changing a signature, use refs to acquire semantic references across affected packages and tests. Read all returned reference rows before dependent edits, continuing incomplete output; report skipped or unavailable coverage rather than treating text matches as complete caller coverage. Usage: `msymbol [--max-tokens N] [--workspace ROOT] (def|refs) PATH [LINE] SYMBOL [N] [(def|refs) PATH [LINE] SYMBOL [N] ...]`. PATH:LINE is also accepted. Without LINE, def and refs select the unique outline declaration named SYMBOL; locals and repeated names need LINE. Batched tuples share a server per language and one output budget; independent tuples continue after a failure. LINE selects the current snapshot. ROOT sets resolver scope and relative paths without changing shell state. N selects an exact language-token occurrence. Ambiguous selectors, unavailable language servers, input changes during the query, and definitions without an editable workspace location fail only the affected tuple, reporting errors on stderr while successful tuples remain on stdout. An incomplete token-limited result retains complete rows, writes stderr, and exits nonzero.\"}"), NativeExecutor: "msymbol"},
		{Specification: []byte("{\"type\":\"custom\",\"name\":\"inspect_file\",\"description\":\"Inspect host-readable regular files and return compact structural rows: START-END KIND NAME. Imports collapse to one range; parse_error rows locate syntax errors. When only structure is needed, prefer an outline to a full-file read; read source only for information missing from the outline or current context.\\nUsage: inspect_file [--json] [--max-tokens N] PATH [PATH ...]\\nMultiple files have path headers and share one budget. Failed paths report errors on stderr (JSON envelopes with --json), preserve successful stdout, and exit nonzero. --json returns metadata and structured outline entries instead. Line ranges are one-based. Example: inspect_file src/main.go, then mcat src/main.go START:END for the relevant entry. Reuse known locations instead of outlining a file again.\"}"), NativeExecutor: "inspect_file"},
		{Specification: []byte("{\"type\":\"custom\",\"name\":\"mread\",\"description\":\"Continue omitted retained output without rerunning its producer. Only emitted references recover retained output; ordinary exec_command truncation has no mread recovery. Usage: `mread REF [REF ...] [--stdout|--stderr] [--max-tokens N]`. REF is a returned handle, not a path or range. Multiple handles share one budget and return one combined next_call. Failed handles report errors on stderr without discarding other handles' stdout; any failure exits nonzero. --stdout or --stderr selects one stream; otherwise both are returned. Source-row pages state their row range.\"}"), NativeExecutor: "mread"},
		{Specification: []byte("{\"type\":\"custom\",\"name\":\"mrun\",\"description\":\"Bound one foreground command's output, retaining its beginning or end. Use for noisy commands when a bounded head or tail is sufficient; output outside the selected window is discarded. Usage: `mrun (-n N|--max-tokens N) [--tail] [--] COMMAND [ARG...]`. Stock yielded sessions and write_stdin still own interactive continuation.\"}"), NativeExecutor: "mrun"},
		{Specification: []byte("{\"type\":\"custom\",\"name\":\"mchanges\",\"description\":\"Review, revert, or reapply captured filesystem changes from stock apply_patch, shell file operations, and supported Python/JS writes; not a Git diff or provisional preview. Usage: `mchanges --list [ID[..ID] ...] [--workspace DIR] [--max-tokens N] | mchanges [--mine | ID[..ID] ...] [--summary|--net] [--workspace DIR] [--max-tokens N] [-- PATH ...] | mchanges revert|apply ID[..ID] ... [--workspace DIR] [--max-tokens N] [-- PATH ...]`. Reuse the change IDs supplied with completed edit receipts; do not run --list when those IDs are already available. Use `mchanges --list` only to recover missing IDs. For handoffs and review requests, give explicit mchanges IDs or same-agent inclusive ranges and the review scope, not vague \\u2018diff\\u2019, \\u2018pending changes\\u2019, or \\u2018pending diff\\u2019 labels. Bare mchanges, --mine, and --list without IDs are scoped to the calling thread, not whole-workspace coverage; --list compresses the caller's IDs with counts; --summary shows diff-pane file statuses and per-path counts. --net composes selected captured diffs, not a live Git diff. Choose editing tools for the task, not capture support. Use mchanges for captured changes. An empty caller-scoped list or a missing completion range does not establish capture failure: obtain the author\\u2019s explicit range and inspect it before falling back to Git. Use a scoped workspace diff or file inspection only for identified uncovered paths or missing baselines. Avoid duplicate reviews of the same evidence; skip --summary before an already-needed diff. `revert` undoes and `apply` replays selected changes in the workspace, git-style: drifted regions merge; overlapping edits leave conflict markers (exit 1). Output states each file relative to mchanges history, not Git (`clean`, `+N -N`, `UU` conflict, `??` unknown). Read modes continue past failed targets, keeping available results on stdout and errors on stderr with nonzero status; apply and revert retain dependency checks. The revert is itself recorded as a change; follow the printed undo line. Recorded diffs are historical evidence, not proof of current workspace contents.\"}"), NativeExecutor: "mchanges"},
	}}
}
