package toolplugin

import (
	"context"
	"embed"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// Keep the generated asset independent of checkout paths and Git metadata.
//
//go:generate env GOOS=wasip1 GOARCH=wasm go build -trimpath -buildvcs=false -buildmode=c-shared "-ldflags=-s -w" -o shared_core.wasm ../../sharedwasm
//go:generate sh -c "rm -f dist/*.js"
//go:generate bun build ../../../plugins/tools.ts ../../../plugins/hrun.ts ../../../plugins/rtk.ts --outdir ./dist --splitting --production --target node --format esm --external mekugi:core/v1 "--banner=// Code generated by Bun from plugins sources. DO NOT EDIT."
//go:embed host.mjs core-v1.mjs shared_core.wasm dist/*.js
var runtimeFiles embed.FS

const (
	APIVersion                  = "mekugi-tool-plugin/v1"
	hostFilename                = "host.mjs"
	snapshotDirectory           = "plugins"
	minimumNodeMajor            = 24
	maxDeclarationFiles         = 64
	maxSnapshotBytes            = 32 << 20
	maxSnapshotFileBytes        = 8 << 20
	ExecutionOutputBudgetBytes  = 16 << 20
	maxExecutionHostOutputBytes = 100 << 20
)

func Load(ctx context.Context, pluginDirectory, snapshotRoot string) (Snapshot, error) {
	if err := ctx.Err(); err != nil {
		return Snapshot{}, err
	}
	if err := os.MkdirAll(snapshotRoot, 0o700); err != nil {
		return Snapshot{}, fmt.Errorf("create plugin snapshot: %w", err)
	}
	host, err := runtimeFiles.ReadFile("host.mjs")
	if err != nil {
		return Snapshot{}, fmt.Errorf("read embedded plugin host: %w", err)
	}
	hostPath := filepath.Join(snapshotRoot, hostFilename)
	if err := os.WriteFile(hostPath, host, 0o600); err != nil {
		return Snapshot{}, fmt.Errorf("write plugin host snapshot: %w", err)
	}

	pluginRoot := filepath.Join(snapshotRoot, snapshotDirectory)
	if err := os.MkdirAll(pluginRoot, 0o700); err != nil {
		return Snapshot{}, fmt.Errorf("create plugin snapshot root: %w", err)
	}
	builtins, err := fs.Sub(runtimeFiles, "dist")
	if err != nil {
		return Snapshot{}, fmt.Errorf("open embedded built-in plugins: %w", err)
	}
	if err := os.CopyFS(filepath.Join(pluginRoot, "builtin"), builtins); err != nil {
		return Snapshot{}, fmt.Errorf("write built-in plugin snapshot: %w", err)
	}
	for _, name := range []string{"core-v1.mjs", "shared_core.wasm"} {
		content, readErr := runtimeFiles.ReadFile(name)
		if readErr != nil {
			return Snapshot{}, fmt.Errorf("read embedded shared core %s: %w", name, readErr)
		}
		if writeErr := os.WriteFile(filepath.Join(pluginRoot, "builtin", name), content, 0o600); writeErr != nil {
			return Snapshot{}, fmt.Errorf("write shared core snapshot %s: %w", name, writeErr)
		}
	}
	modules := []string{"builtin/tools.js"}
	userModules, err := snapshotPluginTree(pluginDirectory, filepath.Join(pluginRoot, "user"))
	if err != nil {
		return Snapshot{}, err
	}
	for _, module := range userModules {
		modules = append(modules, filepath.ToSlash(filepath.Join("user", module)))
	}

	node, err := resolveNodeRuntime(ctx)
	if err != nil {
		return Snapshot{}, err
	}
	plugins, diagnostics, err := validateSnapshot(ctx, node, hostPath, pluginRoot, modules)
	if err != nil {
		return Snapshot{}, err
	}
	return Snapshot{
		Root:           snapshotRoot,
		NodeExecutable: node,
		Plugins:        plugins,
		Diagnostics:    diagnostics,
	}, nil
}

func snapshotPluginTree(sourceRoot, targetRoot string) (modules []string, err error) {
	if err := os.MkdirAll(targetRoot, 0o700); err != nil {
		return nil, fmt.Errorf("create plugin module snapshot: %w", err)
	}
	source, err := os.OpenRoot(sourceRoot)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("open plugin directory: %w", err)
	}
	defer func() { err = errors.Join(err, source.Close()) }()

	entries, err := fs.ReadDir(source.FS(), ".")
	if err != nil {
		return nil, fmt.Errorf("read plugin directory: %w", err)
	}
	for _, entry := range entries {
		info, infoErr := entry.Info()
		if infoErr != nil {
			return nil, fmt.Errorf("inspect plugin declaration %s: %w", entry.Name(), infoErr)
		}
		if !info.Mode().IsRegular() || !(strings.HasSuffix(entry.Name(), ".js") || strings.HasSuffix(entry.Name(), ".mjs")) {
			continue
		}
		modules = append(modules, entry.Name())
	}
	if len(modules) > maxDeclarationFiles {
		return nil, fmt.Errorf("plugin directory contains %d declarations, limit is %d", len(modules), maxDeclarationFiles)
	}
	var total int64
	err = fs.WalkDir(source.FS(), ".", func(relative string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if relative == "." {
			return nil
		}
		topLevel := filepath.Dir(relative) == "."
		info, infoErr := entry.Info()
		if infoErr != nil {
			return infoErr
		}
		targetPath := filepath.Join(targetRoot, filepath.FromSlash(relative))
		if info.IsDir() {
			return os.Mkdir(targetPath, 0o700)
		}
		if !info.Mode().IsRegular() {
			if topLevel {
				return nil
			}
			return fmt.Errorf("plugin dependency %s is not a regular file", relative)
		}
		if info.Size() > maxSnapshotFileBytes {
			return fmt.Errorf("plugin snapshot file %s has %d bytes, limit is %d", relative, info.Size(), maxSnapshotFileBytes)
		}

		sourceFile, openErr := source.Open(relative)
		if openErr != nil {
			return openErr
		}
		before, statErr := sourceFile.Stat()
		if statErr != nil || !before.Mode().IsRegular() || !os.SameFile(info, before) {
			_ = sourceFile.Close()
			if statErr != nil {
				return statErr
			}
			return fmt.Errorf("plugin snapshot file %s changed during discovery", relative)
		}
		target, createErr := os.OpenFile(targetPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
		if createErr != nil {
			_ = sourceFile.Close()
			return createErr
		}
		copied, copyErr := io.Copy(target, io.LimitReader(sourceFile, maxSnapshotFileBytes+1))
		after, afterErr := sourceFile.Stat()
		closeErr := errors.Join(target.Close(), sourceFile.Close())
		if copyErr != nil || afterErr != nil || closeErr != nil {
			return errors.Join(copyErr, afterErr, closeErr)
		}
		if copied > maxSnapshotFileBytes {
			return fmt.Errorf("plugin snapshot file %s has more than %d bytes", relative, maxSnapshotFileBytes)
		}
		if !os.SameFile(before, after) || before.Size() != after.Size() || before.ModTime() != after.ModTime() ||
			copied != before.Size() {
			return fmt.Errorf("plugin snapshot file %s changed while being copied", relative)
		}
		total += copied
		if total > maxSnapshotBytes {
			return fmt.Errorf("plugin snapshot has more than %d bytes", maxSnapshotBytes)
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("snapshot plugin modules: %w", err)
	}
	return modules, nil
}

func resolveNodeRuntime(ctx context.Context) (string, error) {
	ctx, cancel := context.WithTimeout(ctx, pluginInvocationTimeout)
	defer cancel()
	node, err := exec.LookPath("node")
	if err != nil {
		return "", fmt.Errorf("tool plugins require Node.js %d or newer: %w", minimumNodeMajor, err)
	}
	node, err = filepath.EvalSymlinks(node)
	if err != nil {
		return "", fmt.Errorf("resolve Node.js executable: %w", err)
	}
	command := exec.CommandContext(ctx, node, "--version")
	output, err := command.Output()
	if err != nil {
		return "", fmt.Errorf("query Node.js version: %w", err)
	}
	version := strings.TrimSpace(string(output))
	majorText := strings.TrimPrefix(strings.SplitN(version, ".", 2)[0], "v")
	major, err := strconv.Atoi(majorText)
	if err != nil || major < minimumNodeMajor {
		return "", fmt.Errorf("tool plugins require Node.js %d or newer, found %q", minimumNodeMajor, version)
	}
	return node, nil
}

func validateSnapshot(ctx context.Context, node, hostPath, pluginRoot string, modules []string) ([]Plugin, []string, error) {
	ctx, cancel := context.WithTimeout(ctx, pluginInvocationTimeout)
	defer cancel()
	// Resolve against the router environment before the host's PATH is isolated.
	// Absence is reported only if a declaration actually contains a regex.
	regexValidator, lookupErr := exec.LookPath("rg")
	if lookupErr != nil {
		regexValidator = ""
	} else {
		regexValidator, lookupErr = filepath.Abs(regexValidator)
		if lookupErr != nil {
			return nil, nil, fmt.Errorf("resolve regex validator: %w", lookupErr)
		}
	}
	request := struct {
		Operation      string   `json:"operation"`
		SnapshotRoot   string   `json:"snapshotRoot"`
		Modules        []string `json:"modules"`
		RegexValidator string   `json:"regexValidator"`
	}{
		Operation:      "validate",
		SnapshotRoot:   pluginRoot,
		Modules:        modules,
		RegexValidator: regexValidator,
	}
	var response struct {
		Plugins []Plugin `json:"plugins"`
		Errors  []string `json:"errors"`
	}
	err := invoke(ctx, node, hostPath, pluginRoot, "", nil, ExecutionOutputBudgetBytes, nil, nil, request, &response)
	if errors.Is(err, context.DeadlineExceeded) {
		return nil, nil, fmt.Errorf("plugin validation exceeded %s", pluginInvocationTimeout)
	}
	if err != nil {
		return nil, nil, fmt.Errorf("validate tool plugins: %w", err)
	}
	return response.Plugins, response.Errors, nil
}
