package router

// Source: openai/codex codex-rs/protocol/src/protocol.rs.
// Inter-agent message shapes visible at the Responses boundary.

import (
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/yusing/mekugi/internal/commentaryid"
)

const subagentCommentaryMessagePrefix = commentaryid.SubagentPrefix

func subagentCommentaryMessageID(seed string) string {
	digest := sha256.Sum256([]byte(seed))
	return fmt.Sprintf("%s%x", subagentCommentaryMessagePrefix, digest[:12])
}

// Start metadata comes from the child's actual request, not the parent's spawn
// arguments: native roles can override the model and reasoning configuration.
func subagentStartCommentary(request *parsedResponsesRequest, recipient string) string {
	model := request.model()
	var reasoning struct {
		Effort string `json:"effort"`
	}
	if raw, ok := request.fields["reasoning"]; ok {
		if err := json.Unmarshal(raw, &reasoning); err != nil {
			return ""
		}
	}
	tier := jsonString(request.fields, "service_tier")
	if tier == "priority" {
		tier = "fast"
	}
	effort := strings.TrimSpace(reasoning.Effort)
	if model == "" || len(model)+len(effort)+len(tier) > maxCommentaryPublicationBytes || strings.ContainsAny(model+effort+tier, "\r\n\x00") {
		return ""
	}
	renderedEffort := "not specified"
	if effort != "" {
		renderedEffort = commentaryCode(effort)
	}
	renderedTier := "not specified"
	if tier != "" {
		renderedTier = commentaryCode(tier)
	}
	text := "Started.\nModel: " + commentaryCode(model) + "\nReasoning effort: " + renderedEffort + "\nService tier: " + renderedTier
	input, err := decodeResponsesInput(request.fields["input"])
	if err == nil {
		for _, v := range input.items {
			item, ok := decodeResponsesItem(v)
			if !ok {
				continue
			}
			if prompt, assignment := journalAssignmentText(item.fields, recipient); assignment {
				if prompt != "" {
					text += "\n\n**Spawn prompt:**\n\n" + prompt
				}
				break
			}
		}
	}
	return text

}

func prepareSubagentInputCommentary(fields map[string]json.RawMessage, recipient string) []map[string]json.RawMessage {
	var items []map[string]json.RawMessage
	if json.Unmarshal(fields["input"], &items) != nil {
		return nil
	}
	visible := make(map[string]struct{})
	currentInput := 0
	for i, item := range items {
		// A later user message or assistant output makes preceding envelopes
		// historical, even if their commentary was never displayed. This boundary
		// also works on full-history requests after resume or cache rebasing.
		kind, role := jsonString(item, "type"), jsonString(item, "role")
		if (kind == "message" || kind == "") && (role == "user" || role == "assistant") ||
			kind == "reasoning" || strings.HasSuffix(kind, "_call") {
			currentInput = i + 1
		}

		if jsonString(item, "type") == "message" && strings.HasPrefix(jsonString(item, "id"), subagentCommentaryMessagePrefix) {
			visible[jsonString(item, "id")] = struct{}{}
		}
	}
	// Replay cleanup is owned by durable provenance reconciliation. Prefixes
	// alone do not prove that a message was generated by this router.
	// An absent or malformed identity cannot establish that an envelope is
	// addressed to this request.
	if recipient != "/root" && !strings.HasPrefix(recipient, "/root/") || strings.ContainsAny(recipient, "\r\n\x00") {
		return nil
	}

	var commentary []map[string]json.RawMessage
	budget := maxCommentaryPublicationBytes
	for _, item := range items[currentInput:] {
		text, sender, final, ok := subagentResponse(item)
		if !ok || final || jsonString(item, "recipient") != recipient {
			continue
		}
		id := subagentCommentaryMessageID("response\x00" + jsonString(item, "id") + "\x00" + sender + "\x00" + text)
		if _, alreadyVisible := visible[id]; alreadyVisible {
			continue
		}
		direction := "[" + commentaryCode(sender) + " -> " + commentaryCode(recipient) + "] "
		label := direction + "Message received."
		if text != "" {
			label = direction + "Message received:\n" + text
		}
		if len(label) <= budget && len(commentary) < maxCommentaryEventsPerRoute {
			budget -= len(label)
			commentary = append(commentary, assistantCommentaryMessage(id, label))
		}
	}
	return commentary
}

func subagentResponse(item map[string]json.RawMessage) (text, sender string, final, ok bool) {
	if jsonString(item, "type") != "agent_message" {
		return "", "", false, false
	}
	sender = jsonString(item, "author")
	if sender != "/root" && !strings.HasPrefix(sender, "/root/") || strings.ContainsAny(sender, "\r\n\x00") {
		return "", "", false, false
	}
	var content []map[string]json.RawMessage
	if json.Unmarshal(item["content"], &content) != nil {
		return "", "", false, false
	}
	// Native Codex pairs the plaintext routing header with opaque ciphertext.
	// Report receipt only; neither part is a plaintext reply payload.
	if len(content) == 2 && jsonString(content[0], "type") == "input_text" &&
		jsonString(content[1], "type") == "encrypted_content" {
		return "", sender, false, true
	}
	if len(content) != 1 {
		return "", "", false, false
	}
	if jsonString(content[0], "type") == "encrypted_content" {
		return "", sender, false, true
	}
	if jsonString(content[0], "type") != "input_text" {
		return "", "", false, false
	}
	body := jsonString(content[0], "text")
	header, payload, found := strings.Cut(body, "\nPayload:\n")
	if !found || (!strings.HasPrefix(header, "Message Type: MESSAGE\n") && !strings.HasPrefix(header, "Message Type: FINAL_ANSWER\n")) {
		return "", "", false, false
	}
	return payload, sender, strings.HasPrefix(header, "Message Type: FINAL_ANSWER\n"), true
}

// tokenUsageCommentary reports usage only alongside a completed substantive answer.
func tokenUsageCommentary(response []byte, counts tokenUsageReport, observed bool, terminalStatus string) map[string]json.RawMessage {
	return formatTokenUsageCommentary(response, counts, observed, terminalStatus, tokenUsageSubstantive(response))
}

func tokenUsageSubstantive(response []byte) bool {
	var body struct {
		Output []map[string]json.RawMessage `json:"output"`
	}
	if json.Unmarshal(response, &body) != nil {
		return false
	}
	substantive := false
	for _, item := range body.Output {
		if blocksTokenUsage(item) {
			return false
		}
		substantive = substantive || isSubstantiveAnswer(item)
	}
	return substantive
}

func isFinalAnswerMessage(item map[string]json.RawMessage) bool {
	return responseMessageFacts(item).FinalAnswerCandidate()
}

// Source: codex-rs/protocol/src/models.rs ContentItem and MessagePhase.
// Codex drops messages with unsupported content (notably refusal parts).
// JSON and SSE must not make usage the only consumable assistant item.
func isSubstantiveAnswer(item map[string]json.RawMessage) bool {
	if !isFinalAnswerMessage(item) {
		return false
	}
	if status := jsonString(item, "status"); status != "" && status != "completed" {
		return false
	}
	if raw, present := item["phase"]; present {
		var phase *string
		if json.Unmarshal(raw, &phase) != nil || phase != nil && *phase != "final_answer" {
			return false
		}
	}
	var content []struct {
		Type string  `json:"type"`
		Text *string `json:"text"`
	}
	if json.Unmarshal(item["content"], &content) != nil {
		return false
	}
	substantive := false
	for _, part := range content {
		if part.Type != "output_text" || part.Text == nil {
			return false
		}
		substantive = substantive || strings.TrimSpace(*part.Text) != ""
	}
	return substantive

}

// Client dispatches and unfinished hosted calls are not final-answer turns.
func blocksTokenUsage(item map[string]json.RawMessage) bool {
	switch jsonString(item, "type") {
	case "function_call", "custom_tool_call", "computer_call", "local_shell_call", "apply_patch_call", "mcp_approval_request":
		return true
	case "tool_search_call":
		if jsonString(item, "execution") != "server" {
			return true
		}
	case "shell_call":
		var environment map[string]json.RawMessage
		if json.Unmarshal(item["environment"], &environment) != nil || jsonString(environment, "type") != "container_reference" {
			return true
		}
	}
	if strings.HasSuffix(jsonString(item, "type"), "_call") {
		status := jsonString(item, "status")
		return status != "completed" && status != "failed"
	}
	return false
}

func formatTokenUsageCommentary(response []byte, counts tokenUsageReport, observed bool, terminalStatus string, substantive bool) map[string]json.RawMessage {

	if !observed {
		return nil
	}
	var identity struct {
		ID     string `json:"id"`
		Status string `json:"status"`
	}

	if json.Unmarshal(response, &identity) != nil || identity.ID == "" {
		return nil
	}
	status := identity.Status
	if terminalStatus != "" {
		status = terminalStatus
	}
	if status != "completed" {
		return nil
	}
	if !substantive {
		return nil
	}

	text := formatTokenUsageReport(counts)
	id := subagentCommentaryMessageID("usage\x00" + identity.ID)
	return assistantCommentaryMessage(id, text)
}

// responseWithTokenUsageCommentary extracts a response object and token usage commentary.
func responseWithTokenUsageCommentary(response []byte, counts tokenUsageReport, usageObserved bool, terminalStatus string) (
	map[string]json.RawMessage,
	map[string]json.RawMessage,
	error,
) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(response, &object); err != nil || object == nil {
		return nil, nil, errors.New("decode mekugi-enabled response")
	}
	message := tokenUsageCommentary(response, counts, usageObserved, terminalStatus)
	rawOutput, present := object["output"]
	if message == nil || !present {
		return object, message, nil
	}
	var output []map[string]json.RawMessage
	if err := json.Unmarshal(rawOutput, &output); err != nil {
		return nil, nil, errors.New("decode mekugi-enabled response output")
	}
	output = append([]map[string]json.RawMessage{message}, output...)
	encoded, err := marshalProtocolJSON(output)
	if err != nil {
		return nil, nil, err
	}
	object["output"] = encoded
	return object, message, nil
}
